Projects/Django/Exercises/exercise_18_8/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all pizzas.
    url(r'^pizzas/$', views.pizzas, name='pizzas'),

    # Detail page for a single pizza.
    url(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

Projects/Django/Exercises/exercise_18_8/pizzeria/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('pizzas.urls', namespace='pizzas')),
]

Projects/Django/Exercises/exercise_18_8/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    """Defines a model pizza."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """Defines a model called Topping."""
    pizza = models.ForeignKey(Pizza)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

Projects/Django/Exercises/exercise_18_8/pizzas/views.py
from django.shortcuts import render

from .models import Pizza


def index(request):
    """The home page for Learning Log"""
    return render(request, 'pizzas/index.html')


def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    """Show a single pizza, and all its entries."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Projects/Django/Exercises/exercise_18_8/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock %}

Projects/Django/Exercises/exercise_18_8/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
  <h1>Pizzas</h1>
{% endblock content %}

Projects/Django/Exercises/exercise_18_8/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.name|linebreaks }}</p>
    </li>
  {% empty %}
    <li>
      There are no toppings for this pizza yet.
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

Projects/Django/Exercises/exercise_18_8/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>No pizzas have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}