Projects/Django/Exercises/exercise_20_2/Blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('blogs.urls', namespace='blogs')),
]

Projects/Django/Exercises/exercise_20_2/blogs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all blogs.
    url(r'^blogs/$', views.blogs, name='blogs'),

    # Page for adding a new blog.
    url(r'^new_blog/$', views.new_blog, name='new_blog'),

    # Page for editing an blog.
    url(r'^edit_blog/(?P<blog_id>\d+)/$', views.edit_blog,
        name='edit_blog'),
]

Projects/Django/Exercises/exercise_20_2/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Login page.
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),

    # Logout page.
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page.
    url(r'^register/$', views.register, name='register'),
]

Projects/Django/Exercises/exercise_20_2/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    """A blog."""
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

Projects/Django/Exercises/exercise_20_2/users/models.py
from django.db import models

# Create your models here.

Projects/Django/Exercises/exercise_20_2/blogs/forms.py
from django import forms

from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Projects/Django/Exercises/exercise_20_2/blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import BlogPostForm


def index(request):
    """The home page for Blog"""
    return render(request, 'blogs/index.html')


@login_required
def blogs(request):
    """Show all blogs."""
    blogs = BlogPost.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)


@login_required
def new_blog(request):
    """Add a new blog."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('blogs:blogs'))

    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def edit_blog(request, blog_id):
    """Edit an existing blog."""
    blog = BlogPost.objects.get(id=blog_id)
    check_blog_owner(request, blog)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current blog.
        form = BlogPostForm(instance=blog)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:blogs'))

    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)


def check_blog_owner(request, blog):
    """Check currently logged-in user"""
    if blog.owner != request.user:
        raise Http404

Projects/Django/Exercises/exercise_20_2/users/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in, and then redirect to home page.
            authenticated_user = authenticate(
                username=new_user.username,
                password=request.POST['password1']
            )
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

Projects/Django/Exercises/exercise_20_2/blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Blogs</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'blogs:blogs' %}">Blogs</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

Projects/Django/Exercises/exercise_20_2/blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block header %}
  <h1>Blogs</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for blog in blogs %}
      <li>
        <p>{{ blog.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ blog.text|linebreaks }}</p>
        <h4><a href="{% url 'blogs:edit_blog' blog.id %}">edit blog</a></h4>
      </li>
    {% empty %}
      <li>No blogs have been added yet.</li>
    {% endfor %}
  </ul>

  <h4><a href="{% url 'blogs:new_blog' %}">Add a new blog:</a></h4>

{% endblock content %}

Projects/Django/Exercises/exercise_20_2/blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit blog:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'blogs:edit_blog' blog.id %}" method="post" class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}

  </form>

{% endblock content %}

Projects/Django/Exercises/exercise_20_2/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
  <div class='jumbotron'>
      <h2>Create your own blog.</h2>
  </div>
{% endblock %}

Projects/Django/Exercises/exercise_20_2/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new blog:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'blogs:new_blog' %}" method="post" class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add blog</button>
    {% endbuttons %}

  </form>

{% endblock content %}

Projects/Django/Exercises/exercise_20_2/users/templates/users/login.html
{% extends "blogs/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    <input type="hidden" name="next"
      value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}

Projects/Django/Exercises/exercise_20_2/users/templates/users/register.html
{% extends "blogs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}